# Generated by Django 3.1.7 on 2021-03-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvFile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv',
            old_name='profile',
            new_name='path',
        ),
        migrations.RemoveField(
            model_name='csv',
            name='address',
        ),
        migrations.RemoveField(
            model_name='csv',
            name='email',
        ),
        migrations.RemoveField(
            model_name='csv',
            name='name',
        ),
        migrations.RemoveField(
            model_name='csv',
            name='phone',
        ),
        migrations.AddField(
            model_name='csv',
            name='ClassId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csv',
            name='Height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csv',
            name='Roi_x1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csv',
            name='Roi_x2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csv',
            name='Roi_y1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csv',
            name='Roi_y2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csv',
            name='Width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
