# Generated by Django 3.1.7 on 2021-03-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvFile', '0002_auto_20210325_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='Class_name',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
