# Generated by Django 3.1.7 on 2021-03-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imguploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgup',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
