# Generated by Django 3.1.7 on 2021-03-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imguploader', '0003_auto_20210317_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgup',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imgup',
            name='slug',
            field=models.SlugField(blank=True, default='abc'),
        ),
    ]
