# Generated by Django 3.1.7 on 2021-03-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imguploader', '0004_auto_20210318_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgup',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
